### ISSUE TITLE
Random kick on 2018

### ISSUE THREAD

**Issue by why1116** [RealMCoded/Rec.js#5]
**Describe the bug**
When you play on 2018 it randomly kicks you to your dorm.
the console will output playerSubscriptions/v1/update [WS] Responds with Presence update called! thats when you get kicked.

**To Reproduce**
1. Open the server on the dev release.
2. join any room doesn't matter
3. just wait a little bit it should kick you from the game back to your dorm

**System Information:**
 - OS: Windows 10
 - Rec.js Version: 0.1.5
 - Rec.js Commit: c40d820
 - Rec Room Version: March 30 2018

**Comment by notChocoMilk** [comment]
i was actually about to report this as well. it seems to be an issue with the 2018 api it's self, as it happens on multiple builds. if helpful at all, it also gives you a '-2 network error' when kicked to your dorm.

**Comment by RealMCoded** [comment]
> the console will output playerSubscriptions/v1/update [WS] Responds with Presence update called! thats when you get kicked.

This is 100% caused by my implementation of the websocket i am using. It's mostly the same code as the 2017 WS, as it didn't appear to have any issues (at least from my testing). I have started work on a websocket rewrite, but I haven't published any of the code as it isn't ready yet.

**Comment by RealMCoded** [comment]
I pushed a rewrite of the Websocket Server. After staying in the same room for around 10 or so minutes I didn't get kicked at all, so I think this is fixed. I am going to leave this open until I get confirmation that it does fix the issue.

**Comment by why1116** [comment]
that seems to have fixed the issue.

**Comment by why1116** [comment]
Thank you!

**Comment by RealMCoded** [comment]
No problem!

**Comment by why1116** [comment]
but now the microphone doesn't work ingame, oh well

**Comment by RealMCoded** [comment]
That would be an issue with either your photon server or your current user settings.

**Comment by why1116** [comment]
I'll look into that

**Comment by why1116** [comment]
But thanks for being super responsive i can't wait to see what other things you make!

**Comment by RealMCoded** [comment]
No problem! Thank you for the support!!!
